glaucoma-saas-eyepacs/
  backend/
    app/
      main.py
      core/
        config.py
        security.py
      db/
        database.py
        models.py
      routers/
        auth.py
        predict.py
      services/
        mailer.py
        model.py
      requirements.txt
    vercel.json
  frontend/
    package.json
    next.config.js
    .env.local.example
    src/
      lib/api.ts
      pages/
        index.tsx
        register.tsx
        login.tsx
        forgot.tsx
        reset.tsx
        dashboard.tsx
